# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class BodyAnalyzeAndStoreImageBurstApiAnalyzeInstallationIdBurstPost(TypedDict):
    files: list[str]


class InstallationResponseSchema(TypedDict):
    created_at: str | None
    id: str
    last_seen: str | None


class UnitAnalysis(TypedDict):
    action_required: bool
    blinking_leds: NotRequired[list[str]]
    diagnosis: NotRequired[str | None]
    pattern_detected: NotRequired[str | None]
    recommended_action: str
    solid_leds: NotRequired[list[str]]
    status: Literal["ok", "warning", "error", "unknown"]
    summary: str


class ValidationError(TypedDict):
    ctx: NotRequired[dict[str, Any]]
    input: NotRequired[Any]
    loc: list[str | int]
    msg: str
    type: str


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class LatestMeasurementSchema(TypedDict):
    captured_at: NotRequired[str | None]
    chlorine: UnitAnalysis
    installation_id: str
    ph: UnitAnalysis
    pushed_at: NotRequired[str | None]
    raw_response: NotRequired[str | None]
