# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class BodyAnalyzeAndStoreImageBurstApiAnalyzeInstallationIdBurstPost(TypedDict):
    files: list[str]


class DosingProblemSchema(TypedDict):
    chlorine_status: NotRequired[Literal["ok", "warning", "error", "unknown"] | None]
    message: NotRequired[str | None]
    ph_status: NotRequired[Literal["ok", "warning", "error", "unknown"] | None]
    reason: NotRequired[
        Literal[
            "stale_data",
            "chlorine_error",
            "ph_error",
            "chlorine_warning",
            "ph_warning",
            "multiple_units",
            "unknown",
            "none",
        ]
        | None
    ]
    stale: NotRequired[bool]
    state: NotRequired[Literal["OK", "Warning", "Error"] | None]


class InstallationResponseSchema(TypedDict):
    created_at: str | None
    id: str
    last_seen: str | None


class SharedSensorSchema(TypedDict):
    device_class: NotRequired[str | None]
    key: str
    label: str
    preferred_alias: NotRequired[str | None]
    state_class: NotRequired[str | None]
    unit: NotRequired[str | None]
    updated_at: NotRequired[str | None]
    value: str


class SharedSensorUpdateSchema(TypedDict):
    device_class: NotRequired[str | None]
    key: str
    label: str
    state_class: NotRequired[str | None]
    unit: NotRequired[str | None]
    value: str


class UnitAnalysis(TypedDict):
    action_required: bool
    blinking_leds: NotRequired[list[str]]
    diagnosis: NotRequired[str | None]
    pattern_detected: NotRequired[str | None]
    recommended_action: str
    solid_leds: NotRequired[list[str]]
    status: Literal["ok", "warning", "error", "unknown"]
    summary: str


class ValidationError(TypedDict):
    ctx: NotRequired[dict[str, Any]]
    input: NotRequired[Any]
    loc: list[str | int]
    msg: str
    type: str


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class PoolAnalysisSchema(TypedDict):
    chlorine: UnitAnalysis
    ph: UnitAnalysis


class LatestMeasurementSchema(TypedDict):
    captured_at: NotRequired[str | None]
    dosing_problem: NotRequired[DosingProblemSchema | None]
    installation_id: str
    pool: NotRequired[PoolAnalysisSchema | None]
    pushed_at: NotRequired[str | None]
    raw_response: NotRequired[str | None]
    sensors: NotRequired[list[SharedSensorSchema]]
